
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-app:latest
    container_name: docker-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # 로그 볼륨