# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
spec:
  type: NodePort
  selector:
    app: docker-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080